language: node_js

node_js:
  - "10"
  - "12"
  - "14"
  - "15"

matrix:
  fast_finish: true

cache:
  npm: true
  directories:
    - node_modules

before_script: lerna bootstrap

script:
  - npm test
  - lerna run benchmark
